-- Insert Data into INVENTORY_DETAILS Table
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (1, 'Chips', 10);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (2, 'Hide & Seek Biscuit', 35);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (3, 'Apple', 20);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (4, 'Banana', 5);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (5, 'Chicken', 200);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (6, 'Sandwich', 50);
INSERT INTO INVENTORY_DETAILS (ID, ITEM_NAME, PRICE) VALUES (7, 'Pasta', 100);

-- Insert data into USER Table
 INSERT INTO USER ("EMAIL", "PASSWORD","TYPE") VALUES ('abc@gmail.com','abc','Customer');
 INSERT INTO USER ("EMAIL", "PASSWORD","TYPE") VALUES ('akshatgarg@gmail.com','abc','Customer');
 INSERT INTO USER ("EMAIL", "PASSWORD","TYPE") VALUES ('xyz@yahoo.co.in','abc','Customer');
 INSERT INTO USER ("EMAIL", "PASSWORD","TYPE") VALUES ('admin@rest.com', 'admin','Admin');

-- Insert data into FINANCIAL_REPORT Table
INSERT INTO FINANCIAL_REPORT ("ID", "USERID", "BILL_TOTAL","DATE","MONTH","YEAR") VALUES (1, 'xyz@yahoo.co.in', 100,'20','01','2019');
INSERT INTO FINANCIAL_REPORT ("ID", "USERID", "BILL_TOTAL","DATE","MONTH","YEAR") VALUES (2, 'akshatgarg@gmail.com', 650,'11','04','2019');





